services:
  portfolio_tracker:
    build:
      context: .
      args:
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
    ports:
      - "8080:8080"
    environment:
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=${PORT}
    volumes:
      - portfolio_tracker_data:/app/data
    restart: always
    container_name: portfolio_tracker

volumes:
  portfolio_tracker_data:
