services:
  portfolio-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=orchidpharmed
      - PORT=8080
      - API_KEY=${API_KEY}
    volumes:
      - ./data:/app/data
    restart: always
    container_name: gemini-portfolio
